BaByBoi_Project/Pages/CustomerViewPage/PaymentOrder.cshtml.cs
using BaByBoi.DataAccess.Helper;
using BaByBoi.DataAccess.Service.Interface;
using BaByBoi.DataAccess.Service.VNpayService;
using BaByBoi.Domain.Models;
using BaByBoi_Project.Common.Enum;
using BaByBoi_Project.Extensions;
using FUMiniHotelManagement.Hubs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;

namespace BaByBoi_Project.Pages.CustomerViewPage
{
    public class PaymentOrderModel : PageModel
    {
        private readonly IProductService _productService;
        private readonly IOrderService _orderService;
        private readonly IPaymentService _paymentService;
        private readonly IVnpayService _vnpayService;
        private readonly IVoucherService _voucherService;
        private readonly IHubContext<SignalrServer> _signalRHub;

        public PaymentOrderModel(IProductService productService, IOrderService orderService, IPaymentService paymentService, IVnpayService vnpayService, IVoucherService voucherService, IHubContext<SignalrServer> signalRHub)
        {
            _productService = productService;
            _orderService = orderService;
            _paymentService = paymentService;
            _vnpayService = vnpayService;
            _voucherService = voucherService;
            _signalRHub = signalRHub;
        }
        public List<Payment> paymentMethod { get; set; }
        public List<OrderDetail> orderDetailsPurchase { get; set; }
        public Order order { get; set; } = new Order
        {
            OrderCode = Guid.NewGuid().ToString()
        };

        public double totalPay { get; set; }

        public User Customer { get; set; }
        public Voucher voucher { get; set; }
        private void getShoppingCartFromSession()
        {
            orderDetailsPurchase = HttpContext.Session.GetObjectFromJson<List<OrderDetail>>("ListPurchase") ?? new List<OrderDetail>();
        }

        private async Task getPaymnetMethod()
        {
            paymentMethod = await _paymentService.getAllPaymentMethod();
        }
        private void SetSuccessMessage(string message)
        {
            TempData["SuccessMessage"] = message;
        }

        private void SetErrorMessage(string message)
        {
            TempData["ErrorMessage"] = message;
        }
        private void getCustomerFromSession()
        {
            Customer = HttpContext.Session.GetObjectFromJson<User>("User");
        }

        private void LoadMessagesFromTempData()
        {
            if (TempData.ContainsKey("SuccessMessage"))
            {
                ViewData["SuccessMessage"] = TempData["SuccessMessage"];
            }
            if (TempData.TryGetValue("ErrorMessage", out var errorMessage))
            {
                ViewData["ErrorMessage"] = errorMessage;
            }
        }

        public async Task OnGet()
        {
            LoadMessagesFromTempData();
            getShoppingCartFromSession();
            getCustomerFromSession();
            foreach (var item in orderDetailsPurchase)
            {
                totalPay += (double)(Math.Ceiling((double)(item.ProductSize.Price - (item.ProductSize.Price * item.Product.Discount) / 100)!) * item.Quantity)!;
            }
            await getPaymnetMethod();

            // Lấy mã voucher từ session
            var appliedVoucherCode = HttpContext.Session.GetString("AppliedVoucher");
            if (!string.IsNullOrEmpty(appliedVoucherCode))
            {
                voucher = await _voucherService.getVoucherByCode(appliedVoucherCode);
                if (voucher != null && DateTime.Now >= voucher.StartDate && DateTime.Now <= voucher.EndDate && voucher.Status == (int)StatusExist.Exist)
                {
                    var discount = totalPay * voucher.Percent!.Value / 100;
                    if (discount > voucher.TriggerValue)
                    {
                        discount = voucher.TriggerValue.Value;
                    }
                    totalPay = totalPay - discount;
                }
            }
        }

        public async Task<IActionResult> OnPostVnpayAction(int paymentId, double totalPrice, int voucherId)
        {
            getShoppingCartFromSession();
            var paymentMethod = await _paymentService.getPayment(paymentId);
            if (paymentMethod.PaymentName!.ToLower().Equals(PayMethod.VNPay.ToLower()))
            {
                var vnpayModel = new VNPaymentRequestModel
                {
                    TotalPrice = totalPrice,
                    CreatedDate = DateTime.Now,
                    Descriptuon = $"Thanh toán đơn hàng tại BabiBoi Store lúc {DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss")}",
                    OrderCode = order.OrderCode!,
                };
                return Redirect(_vnpayService.CreatePaymentUrl(HttpContext, vnpayModel, paymentId, totalPrice, voucherId));
            }
            return RedirectToPage(new { handler = "PlaceOrder", paymentId, totalPrice, orderCode = order.OrderCode, voucherId = voucherId });
        }

        public async Task<IActionResult> OnPostApplyVoucher(string voucherCode)
        {
            LoadMessagesFromTempData();
            getShoppingCartFromSession();
            getCustomerFromSession();
            await getPaymnetMethod();
            voucher = await _voucherService.getVoucherByCode(voucherCode);
            foreach (var item in orderDetailsPurchase)
            {
                totalPay += (double)(Math.Ceiling((double)(item.ProductSize.Price - (item.ProductSize.Price * item.Product.Discount) / 100)!) * item.Quantity)!;
            }

            if (voucher == null || DateTime.Now < voucher.StartDate || DateTime.Now > voucher.EndDate || voucher.Status != (int)StatusExist.Exist)
            {
                ViewData["ErrorMessage"] = "Voucher đã hết hạn";
            }
            else
            {
                var discount = totalPay * (voucher.Percent!.Value) / 100;
                if (discount > voucher.TriggerValue)
                {
                    discount = voucher.TriggerValue.Value;
                }
                totalPay = totalPay - discount;

                // Lưu voucher vào session
                HttpContext.Session.SetString("AppliedVoucher", voucherCode);
            }
            return this.Page();
        }

        public async Task<IActionResult> OnGetPlaceOrder(int paymentID, double totalPrice, string orderCode, int voucherId)
        {
            getShoppingCartFromSession();
            if (orderDetailsPurchase == null || orderDetailsPurchase.Count() == 0)
            {
                return RedirectToPage("ShoppingCart");

            }
            getCustomerFromSession();
            if (Customer == null)
            {
                return RedirectToPage("/Guest/LoginPage/Index");
            }

            var payResponse = _vnpayService.PaymentExecute(Request.Query);

            order.OrderCode = orderCode;
            order.PaymentId = paymentID;
            order.TotalProduct = orderDetailsPurchase.Count();
            order.OrderDetails = orderDetailsPurchase;
            order.TotalPrice = totalPrice;
            order.UserId = Customer.UserId;
            if (voucherId != 0)
            {
                order.VoucherId = voucherId;
            }

            orderDetailsPurchase.ForEach(od =>
            {
                od.Order = null!;
                od.Product = null!;
                od.ProductSize = null!;
            });

            var result = await _orderService.Insert(order);
            HttpContext.Session.Remove("ListPurchase");
            HttpContext.Session.Remove("OrderList");
            if (result != null)
            {
                TempData["SuccessMessage"] = "Đã đặt hàng thành công";

                int newOrderCount = await _orderService.GetNewOrderCountAsync();
                int allOrderCount = await _orderService.GetAllOrderCountAsync();

                await _signalRHub.Clients.All.SendAsync("ReceiveNewOrderCount", newOrderCount);
                await _signalRHub.Clients.All.SendAsync("ReceiveAllOrderCount", allOrderCount);
                await _signalRHub.Clients.All.SendAsync("ReceiveNewOrder");

                return RedirectToPage("/HistoryOrder/Detail", new { orderCode = order.OrderCode });
            }
            return this.Page();
        }
    }
}

BaByBoi_Project/Pages/CustomerViewPage/ProductDetail.cshtml.cs
using BaByBoi.DataAccess.Service.Interface;
using BaByBoi.Domain.Models;
using BaByBoi.Domain.PaginModel;
using BaByBoi_Project.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Drawing.Printing;

namespace BaByBoi_Project.Pages.CustomerViewPage
{
    public class ProductDetailModel : PageModel
    {
        private readonly IProductService _productService;

        public ProductDetailModel(IProductService productService)
        {
            _productService = productService;
        }

        public Product Product { get; set; } = new Product();
        
        public User Customer { get; set; }

        public List<Product> recomendProduct = new List<Product>();
        public async Task OnGet(int productId, int categoryID)
        {
            await LoadDataAsync(productId: productId, categoryID: categoryID);
        }

        public async Task LoadDataAsync(int productId, int categoryID)
        {
            if (productId > 0)
            {
                Product = await _productService.GetProductByProductId(productId);
            }
            if (categoryID > 0)
            {
                var rcm = await _productService.GetAllProduct();
                recomendProduct = rcm.ToList();
            }

            if (TempData.ContainsKey("SuccessMessage"))
            {
                ViewData["SuccessMessage"] = TempData["SuccessMessage"];
            }
            if (TempData.TryGetValue("ErrorMessage", out var errorMessage))
            {
                ViewData["ErrorMessage"] = errorMessage;
            }
        }
        public async Task<IActionResult> OnGetAddToCartAsync(int productId, int sizeId, int categoryId)
        {
            List<OrderDetail> OrderList = HttpContext.Session.GetObjectFromJson<List<OrderDetail>>("OrderList") ?? new List<OrderDetail>();
            var product = await _productService.getProductById(productId);
            var productSize = await _productService.GetProductsSizesBySpecificSizeAsync(productId, sizeId);
            var orderDetail = new OrderDetail
            {
                ProductId = productSize.ProductId,
                Price = Math.Ceiling((double)(productSize.Price - (productSize.Price * product.Discount) / 100)!),
                Quantity = 1,
                Product = product,
                SizeId = productSize.SizeId,
                ProductSize = productSize

            };

            if (OrderList.Where(x => x.ProductId == orderDetail.ProductId && x.ProductSize.SizeId == orderDetail.SizeId).FirstOrDefault() == null)
            {
                OrderList.Add(orderDetail);
                HttpContext.Session.SetObjectAsJson("OrderList", OrderList);
            }
            await LoadDataAsync(productId:productId, categoryID: categoryId);
            return this.Page();
        }
    }
}

BaByBoi_Project/Pages/CustomerViewPage/ShoppingCart.cshtml.cs
using BaByBoi.DataAccess.Service.Interface;
using BaByBoi.Domain.Models;
using BaByBoi_Project.Common;
using BaByBoi_Project.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BaByBoi_Project.Pages.CustomerViewPage
{
    public class ShoppingCartModel : PageModel
    {
        private readonly IProductService _productService;

        public ShoppingCartModel(IProductService productService)
        {
            _productService = productService;
        }

        [BindProperty]
        public List<string> SelectedProducts { get; set; }
        public List<OrderDetail> OrderList { get; set; } = new List<OrderDetail>();
        public User Customer { get; set; }
        private void getShoppingCartFromSession()
        {
            OrderList = HttpContext.Session.GetObjectFromJson<List<OrderDetail>>("OrderList") ?? new List<OrderDetail>();
        }
        private void getCustomerFromSession()
        {
            Customer = HttpContext.Session.GetObjectFromJson<User>("User");
        }
        private void LoadMessagesFromTempData()
        {
            if (TempData.ContainsKey("SuccessMessage"))
            {
                ViewData["SuccessMessage"] = TempData["SuccessMessage"];
            }
            if (TempData.TryGetValue("ErrorMessage", out var errorMessage))
            {
                ViewData["ErrorMessage"] = errorMessage;
            }
        }

        public void OnGet()
        {
            getCustomerFromSession();
            getShoppingCartFromSession();
            LoadMessagesFromTempData();
        }
        public IActionResult OnPostDeleteInCart(int ProductId, int SizeId)
        {
            getShoppingCartFromSession();
            var product = OrderList.FirstOrDefault(x => x.ProductId == ProductId && x.SizeId == SizeId);
            if (product != null)
            {
                OrderList.Remove(product);
            }
            SaveBookingListToSession();
            SetSuccessMessage("Room deleted successfully.");
            return this.Page();
        }
        private void SaveBookingListToSession()
        {
            HttpContext.Session.SetObjectAsJson("OrderList", OrderList);
        }
        public IActionResult OnPostUpdateInCart(int ProductId, string Quantity, int SizeId)
        {
            getShoppingCartFromSession();
            var product = OrderList.FirstOrDefault(x => x.ProductId == ProductId && x.SizeId == SizeId);
            if (product != null)
            {
                //product.Price = Quantity * product.Price;
                product.Quantity = product.ProductSize.Quantity > int.Parse(Quantity) ? int.Parse(Quantity) : product.ProductSize.Quantity;
                SaveBookingListToSession();
                SetSuccessMessage("Cập nhật giỏ hàng thành công");
            }
            else
            {
                SetErrorMessage("Không tìm thấy sản phẩm này.");
            }
            return this.Page();
        }

        public IActionResult UpdateTextQuantity(int ProductId, string quantities, int SizeId)
        {
            getShoppingCartFromSession();
            var product = OrderList.FirstOrDefault(x => x.ProductId == ProductId && x.SizeId == SizeId);
            if (product != null)
            {
                //product.Price = Quantity * product.Price;
                product.Quantity = product.ProductSize.Quantity > int.Parse(quantities) ? int.Parse(quantities) : product.ProductSize.Quantity;
                SaveBookingListToSession();
                SetSuccessMessage("Cập nhật giỏ hàng thành công");
            }
            else
            {
                SetErrorMessage("Không tìm thấy sản phẩm này.");
            }
            return this.Page();
        }

        public IActionResult OnPostPurchase()
        {
            getShoppingCartFromSession();
            getCustomerFromSession();
            if (SelectedProducts != null && SelectedProducts.Any())
            {
                var purchase = new List<OrderDetail>();
                // Xử lý mua các sản phẩm đã chọn
                foreach (var prosize in SelectedProducts)
                {
                    var eachProduct = ProductSizeHelper.cutID(prosize);
                    var orderDetail = OrderList.Where(x => x.ProductId == eachProduct.ProductId && x.SizeId == eachProduct.SizeId).FirstOrDefault();
                    if (eachProduct != null)
                    {
                        purchase.Add(orderDetail!);
                    }
                }
                HttpContext.Session.SetObjectAsJson("ListPurchase", purchase);
                return RedirectToPage("PaymentOrder"); // chuyển qua trang in ra bill chứ chưa thực sự payment vì còn áp dụng voucher
                // thực hiện logic mua hàng, ví dụ: lưu vào cơ sở dữ liệu, gửi email, v.v.
            }
            SetErrorMessage("No products selected for purchase.");
            return this.Page();
        }
        private void SetSuccessMessage(string message)
        {
            TempData["SuccessMessage"] = message;
        }

        private void SetErrorMessage(string message)
        {
            TempData["ErrorMessage"] = message;
        }
    }
}

BaByBoi_Project/Pages/CustomerViewPage/PaymentOrder.cshtml
@page
@using BaByBoi.DataAccess.Utils
@model BaByBoi_Project.Pages.CustomerViewPage.PaymentOrderModel
@{
    Layout = "PaymentLayout";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - BaByBoi Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <style>
        .container {
            margin-top: 20px;
            max-width: 900px;
        }

        .address-container, .order-details, .payment-method {
            border: 1px solid #ddd;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 10px;
        }

            .order-details .row {
                margin-bottom: 10px;
            }

        .total-price {
            font-size: 24px;
            font-weight: bold;
            color: #ff5722;
        }

        .btn-submit {
            width: 100%;
            background-color: #ff5722;
            color: white;
            font-size: 20px;
            padding: 10px;
        }

        .voucher-section {
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
            margin-bottom: 20px;
        }

            .voucher-section .form-group {
                flex-grow: 1;
                margin-right: 10px;
            }
    </style>
</head>
<body>
    <div class="container">
        <!-- Order Details -->
        <div class="order-details" style="margin-top: 200px;">
            <h4>Chi tiết đơn hàng</h4>
            @{
                var priceEachProduct = new double();
            }
            <div class="row">
                @foreach (var item in Model.orderDetailsPurchase)
                {
                    <div class="col-2">
                        <img src="@item.Product.ProductImages.FirstOrDefault()!.ImageUrl" alt="@item.Product.ProductName" class="img-fluid" />
                    </div>
                    <div class="col-4">
                        <p>@item.Product.ProductName</p>
                        <p>Size: @item.ProductSize.Size.SizeName</p>
                    </div>
                    <div class="col-2">
                        <p>@(  (Math.Ceiling( (double)(item.ProductSize.Price - (item.ProductSize.Price * item.Product.Discount) / 100)!) ).ToVietnameseCurrency()  )</p>
                    </div>
                    <div class="col-2">
                        <p>Quantity: @item.Quantity</p>
                    </div>
                    <div class="col-2">
                        @{
                            priceEachProduct = (double)(Math.Ceiling((double)(item.ProductSize.Price - (item.ProductSize.Price * item.Product.Discount) / 100)!) * item.Quantity)!;
                        }
                        <p>@(priceEachProduct.ToVietnameseCurrency() )</p>
                    </div>
                }
            </div>
            <hr />
            <div class="row">
                <div class="col-12 text-end">
                    <p class="total-price">Tổng:  @(Model.totalPay.ToVietnameseCurrency())</p>
                </div>
            </div>
        </div>

        <!-- Voucher Input -->
        <form method="post" class="voucher-section">
            <div class="form-group">
                <label for="voucherCode">Mã giảm giá</label>
                <input type="text" class="form-control" name="voucherCode" placeholder="Nhập mã giảm giá" />
            </div>
            <button asp-page-handler="ApplyVoucher" type="submit" class="btn btn-primary">Áp dụng</button>
        </form>

        @if (Model.voucher != null)
        {
            <div class="row">
                <div class="col-12">
                    <p>Voucher Applied: <strong>@Model.voucher.VoucherCode</strong></p>
                </div>
            </div>
        }

        <!-- Payment Method -->
        <form method="post">
            @if (Model.paymentMethod != null)
            {
                <div class="payment-method">
                    <h4>Phương thức thanh toán</h4>
                    @{
                        var paymentDefault = "Cash on Delivery";
                    }
                    @foreach (var paymethod in Model.paymentMethod)
                    {
                        if (paymethod.PaymentName!.Equals(paymentDefault))
                        {
                            <input type="radio" id="@paymethod.PaymentName" name="paymentID" value="@paymethod.PaymentId" checked="checked" />
                            <label for="@paymethod.PaymentName">Thanh toán khi nhận hàng</label>
                        }
                        else
                        {
                            <input type="radio" id="@paymethod.PaymentName" name="paymentID" value="@paymethod.PaymentId" />
                            <label for="@paymethod.PaymentName">@paymethod.PaymentName</label>
                        }
                    }
                </div>
            }

            <!-- Submit Button -->
            <div class="row">
                <div class="col-12">
                    <input type="hidden" name="totalPrice" value="@Model.totalPay" />
                    @if (Model.voucher != null)
                    {
                        <input type="hidden" name="voucherId" value="@Model.voucher.VoucherId" />
                    }
                    <button asp-page-handler="VnpayAction" type="submit" class="btn btn-submit">Đặt hàng</button>
                </div>
            </div>
        </form>
    </div>

    <script>
        function placeOrder() {
            var selectedPaymentID = document.querySelector('input[name="paymentID"]:checked').value;
            document.getElementById("paymentID").value = selectedPaymentID;
            document.getElementById("placeOrderForm").submit();
        }
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

BaByBoi_Project/Pages/CustomerViewPage/ShoppingCart.cshtml
@page
@using BaByBoi.DataAccess.Utils
@model ShoppingCartModel
@{
    ViewData["Title"] = "Shopping Cart";
    Layout = "UsersLayout";
    var totalCart = new double();
}

<div class="container-fluid py-5">
    <form method="post">
        <div class="container py-5">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Chọn</th>
                            <th scope="col">Sản phẩm</th>
                            <th scope="col">Tên</th>
                            <th scope="col">Size</th>
                            <th scope="col">Giá</th>
                            <th scope="col">Số Lượng</th>
                            <th scope="col">Tổng</th>
                            <th scope="col">Quản lí</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.OrderList)
                        {
                            <tr>
                                <td>
                                    <input class="mt-4" type="checkbox" name="SelectedProducts" value="@item.ProductId-@item.SizeId" />
                                </td>
                                <td scope="row">
                                    <div class="d-flex align-items-center">
                                        <img src="@item.Product.ProductImages.FirstOrDefault()!.ImageUrl" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
                                    </div>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">@item.Product.ProductName</p>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">@item.Product.ProductSizes.FirstOrDefault(x => x.SizeId == item.SizeId && x.ProductId == item.ProductId)!.Size.SizeName</p>
                                </td>
                                <td>
                                    @{
                                        var priceAfterDiscount = Math.Ceiling((double)(item.Price - (item.Price * item.Product.Discount) / 100)!);
                                    }

                                    <p class="mb-0 mt-4">@(priceAfterDiscount.ToVietnameseCurrency())</p>
                                </td>
                                <td>
                                    <div class="input-group quantity mt-4" style="width: 100px;">
                                        <div class="input-group-btn">
                                            @if (item.Quantity <= 1)
                                            {
                                                <button type="submit" asp-page-handler="UpdateInCart" asp-route-ProductId="@item.ProductId" asp-route-Quantity="@(item.Quantity - 1)" asp-route-SizeId="@item.SizeId" class="btn btn-sm btn-minus rounded-circle bg-light border" disabled>
                                                    <i class="fa fa-minus"></i>
                                                </button>
                                            }
                                            else
                                            {
                                                <button type="submit" asp-page-handler="UpdateInCart" asp-route-ProductId="@item.ProductId" asp-route-Quantity="@(item.Quantity - 1)" asp-route-SizeId="@item.SizeId" class="btn btn-sm btn-minus rounded-circle bg-light border">
                                                    <i class="fa fa-minus"></i>
                                                </button>
                                            }
                                        </div>

                                        <input type="text" onkeypress="return /\d/.test(String.fromCharCode(((event||window.event).which||(event||window.event).which)));" onchange="this.form.submit()" name="quantities" value="@item.Quantity" class="form-control form-control-sm text-center border-0" min="1" max="@(item.ProductSize.Quantity)">
                                        
                                        <div class="input-group-btn">
                                            @if (item.ProductSize.Quantity > item.Quantity)
                                            {
                                                <button type="submit" asp-page-handler="UpdateInCart" asp-route-ProductId="@item.ProductId" asp-route-Quantity="@(item.Quantity + 1)" asp-route-SizeId="@item.SizeId" class="btn btn-sm btn-plus rounded-circle bg-light border">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            }
                                            else
                                            {
                                                <button type="submit" asp-page-handler="UpdateInCart" asp-route-ProductId="@item.ProductId" asp-route-Quantity="@(item.Quantity + 1)" asp-route-SizeId="@item.SizeId" class="btn btn-sm btn-plus rounded-circle bg-light border" disabled>
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            }
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">@((item.Quantity * priceAfterDiscount)!.Value.ToVietnameseCurrency() )</p>
                                    @{
                                        totalCart += (double)(item.Quantity * priceAfterDiscount)!;
                                    }
                                </td>
                                <td>
                                    <button type="submit" asp-page-handler="DeleteInCart" asp-route-ProductId="@item.ProductId" asp-route-SizeId="@item.SizeId" class="btn btn-md rounded-circle bg-light border mt-4">
                                        <i class="fa fa-times text-danger"></i>
                                    </button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="mt-5">
            </div>
            <div class="row g-4 justify-content-end">
                <div class="col-8"></div>
                <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
                    <div class="bg-light rounded">
                        <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
                            <h5 class="mb-0 ps-4 me-4">Tổng</h5>
                            <p class="mb-0 pe-4">@totalCart.ToVietnameseCurrency()</p>
                        </div>
                        <button asp-page-handler="Purchase" class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4" type="submit">Tiến hành thanh toán</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    function submitHiddenForm(productId, quantity, sizeId) {
        const form = document.getElementById('hiddenForm');
        form.ProductId.value = productId;
        form.Quantity.value = quantity;
        form.SizeId.value = sizeId;
        form.submit();
    }

    // Gọi hàm submitHiddenForm khi số lượng thay đổi
    function onQuantityChange(inputElement, productId, sizeId) {
        var quantity = inputElement.value;
        submitHiddenForm(productId, quantity, sizeId);
    }
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="lib/easing/easing.min.js"></script>
<script src="lib/waypoints/waypoints.min.js"></script>
<script src="lib/lightbox/js/lightbox.min.js"></script>
<script src="lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Template Javascript -->
<script src="~/js/main.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://kit.fontawesome.com/d98e41de81.js" crossorigin="anonymous"></script>